services:
  - type: web
    name: kuangye-camping
    runtime: node
    buildCommand: ./build.sh
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production
    plan: free
